# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yufujimoto/GitHub/tetheredShooting/ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 822)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/ic_add_a_photo_black_24dp_2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab_control = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_control.setMinimumSize(QtCore.QSize(400, 0))
        self.tab_control.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tab_control.setFont(font)
        self.tab_control.setIconSize(QtCore.QSize(24, 24))
        self.tab_control.setObjectName("tab_control")
        self.tab_prj_item = QtWidgets.QWidget()
        self.tab_prj_item.setObjectName("tab_prj_item")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_prj_item)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lay_h_dir_root = QtWidgets.QHBoxLayout()
        self.lay_h_dir_root.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_dir_root.setObjectName("lay_h_dir_root")
        self.lbl_prjDir = QtWidgets.QLabel(self.tab_prj_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_prjDir.sizePolicy().hasHeightForWidth())
        self.lbl_prjDir.setSizePolicy(sizePolicy)
        self.lbl_prjDir.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_prjDir.setObjectName("lbl_prjDir")
        self.lay_h_dir_root.addWidget(self.lbl_prjDir)
        self.lbl_prj_path = QtWidgets.QLabel(self.tab_prj_item)
        self.lbl_prj_path.setText("")
        self.lbl_prj_path.setObjectName("lbl_prj_path")
        self.lay_h_dir_root.addWidget(self.lbl_prj_path)
        self.verticalLayout_7.addLayout(self.lay_h_dir_root)
        self.tre_prj_item = QtWidgets.QTreeWidget(self.tab_prj_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tre_prj_item.sizePolicy().hasHeightForWidth())
        self.tre_prj_item.setSizePolicy(sizePolicy)
        self.tre_prj_item.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tre_prj_item.setFont(font)
        self.tre_prj_item.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tre_prj_item.setLineWidth(1)
        self.tre_prj_item.setColumnCount(2)
        self.tre_prj_item.setObjectName("tre_prj_item")
        self.tre_prj_item.header().setDefaultSectionSize(150)
        self.tre_prj_item.header().setHighlightSections(False)
        self.verticalLayout_7.addWidget(self.tre_prj_item)
        self.tab_control.addTab(self.tab_prj_item, "")
        self.tab_prj_cam = QtWidgets.QWidget()
        self.tab_prj_cam.setObjectName("tab_prj_cam")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_prj_cam)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lay_h_cam_detect = QtWidgets.QHBoxLayout()
        self.lay_h_cam_detect.setObjectName("lay_h_cam_detect")
        self.lbl_cam_detected = QtWidgets.QLabel(self.tab_prj_cam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cam_detected.sizePolicy().hasHeightForWidth())
        self.lbl_cam_detected.setSizePolicy(sizePolicy)
        self.lbl_cam_detected.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_cam_detected.setMaximumSize(QtCore.QSize(16777215, 200))
        self.lbl_cam_detected.setObjectName("lbl_cam_detected")
        self.lay_h_cam_detect.addWidget(self.lbl_cam_detected)
        self.btn_cam_detect = QtWidgets.QPushButton(self.tab_prj_cam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cam_detect.sizePolicy().hasHeightForWidth())
        self.btn_cam_detect.setSizePolicy(sizePolicy)
        self.btn_cam_detect.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_cam_detect.setObjectName("btn_cam_detect")
        self.lay_h_cam_detect.addWidget(self.btn_cam_detect)
        self.verticalLayout_2.addLayout(self.lay_h_cam_detect)
        self.grp_cam = QtWidgets.QGroupBox(self.tab_prj_cam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_cam.sizePolicy().hasHeightForWidth())
        self.grp_cam.setSizePolicy(sizePolicy)
        self.grp_cam.setMinimumSize(QtCore.QSize(0, 400))
        self.grp_cam.setMaximumSize(QtCore.QSize(400, 16777215))
        self.grp_cam.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.grp_cam.setObjectName("grp_cam")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grp_cam)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_cam_qoi = QtWidgets.QLabel(self.grp_cam)
        self.lbl_cam_qoi.setObjectName("lbl_cam_qoi")
        self.gridLayout_4.addWidget(self.lbl_cam_qoi, 7, 0, 1, 1)
        self.cbx_cam_epg = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_epg.setObjectName("cbx_cam_epg")
        self.gridLayout_4.addWidget(self.cbx_cam_epg, 9, 1, 1, 1)
        self.cbx_cam_size = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_size.setObjectName("cbx_cam_size")
        self.gridLayout_4.addWidget(self.cbx_cam_size, 1, 1, 1, 1)
        self.lbl_cam_fmod = QtWidgets.QLabel(self.grp_cam)
        self.lbl_cam_fmod.setObjectName("lbl_cam_fmod")
        self.gridLayout_4.addWidget(self.lbl_cam_fmod, 8, 0, 1, 1)
        self.lbl_cam_epg = QtWidgets.QLabel(self.grp_cam)
        self.lbl_cam_epg.setObjectName("lbl_cam_epg")
        self.gridLayout_4.addWidget(self.lbl_cam_epg, 9, 0, 1, 1)
        self.lbl_cam_size = QtWidgets.QLabel(self.grp_cam)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cam_size.sizePolicy().hasHeightForWidth())
        self.lbl_cam_size.setSizePolicy(sizePolicy)
        self.lbl_cam_size.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lbl_cam_size.setObjectName("lbl_cam_size")
        self.gridLayout_4.addWidget(self.lbl_cam_size, 1, 0, 1, 1)
        self.cbx_cam_fmod = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_fmod.setObjectName("cbx_cam_fmod")
        self.gridLayout_4.addWidget(self.cbx_cam_fmod, 8, 1, 1, 1)
        self.lbl_cam_iso = QtWidgets.QLabel(self.grp_cam)
        self.lbl_cam_iso.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lbl_cam_iso.setObjectName("lbl_cam_iso")
        self.gridLayout_4.addWidget(self.lbl_cam_iso, 3, 0, 1, 1)
        self.cbx_cam_iso = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_iso.setObjectName("cbx_cam_iso")
        self.gridLayout_4.addWidget(self.cbx_cam_iso, 3, 1, 1, 1)
        self.lbl_cam_cpt = QtWidgets.QLabel(self.grp_cam)
        self.lbl_cam_cpt.setObjectName("lbl_cam_cpt")
        self.gridLayout_4.addWidget(self.lbl_cam_cpt, 10, 0, 1, 1)
        self.lbl_cam_fval = QtWidgets.QLabel(self.grp_cam)
        self.lbl_cam_fval.setObjectName("lbl_cam_fval")
        self.gridLayout_4.addWidget(self.lbl_cam_fval, 6, 0, 1, 1)
        self.lbl_cam_wht = QtWidgets.QLabel(self.grp_cam)
        self.lbl_cam_wht.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lbl_cam_wht.setObjectName("lbl_cam_wht")
        self.gridLayout_4.addWidget(self.lbl_cam_wht, 4, 0, 1, 1)
        self.cbx_cam_cpt = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_cpt.setObjectName("cbx_cam_cpt")
        self.gridLayout_4.addWidget(self.cbx_cam_cpt, 10, 1, 1, 1)
        self.cbx_cam_wht = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_wht.setObjectName("cbx_cam_wht")
        self.gridLayout_4.addWidget(self.cbx_cam_wht, 4, 1, 1, 1)
        self.lbl_cam_exp = QtWidgets.QLabel(self.grp_cam)
        self.lbl_cam_exp.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lbl_cam_exp.setObjectName("lbl_cam_exp")
        self.gridLayout_4.addWidget(self.lbl_cam_exp, 5, 0, 1, 1)
        self.cbx_cam_exp = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_exp.setObjectName("cbx_cam_exp")
        self.gridLayout_4.addWidget(self.cbx_cam_exp, 5, 1, 1, 1)
        self.lbl_cam_met = QtWidgets.QLabel(self.grp_cam)
        self.lbl_cam_met.setObjectName("lbl_cam_met")
        self.gridLayout_4.addWidget(self.lbl_cam_met, 11, 0, 1, 1)
        self.cbx_cam_met = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_met.setObjectName("cbx_cam_met")
        self.gridLayout_4.addWidget(self.cbx_cam_met, 11, 1, 1, 1)
        self.cbx_cam_fval = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_fval.setObjectName("cbx_cam_fval")
        self.gridLayout_4.addWidget(self.cbx_cam_fval, 6, 1, 1, 1)
        self.cbx_cam_qoi = QtWidgets.QComboBox(self.grp_cam)
        self.cbx_cam_qoi.setObjectName("cbx_cam_qoi")
        self.gridLayout_4.addWidget(self.cbx_cam_qoi, 7, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.grp_cam)
        self.tab_control.addTab(self.tab_prj_cam, "")
        self.horizontalLayout.addWidget(self.tab_control)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tab_target = QtWidgets.QTabWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_target.sizePolicy().hasHeightForWidth())
        self.tab_target.setSizePolicy(sizePolicy)
        self.tab_target.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_target.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tab_target.setFont(font)
        self.tab_target.setAutoFillBackground(False)
        self.tab_target.setIconSize(QtCore.QSize(24, 24))
        self.tab_target.setTabsClosable(False)
        self.tab_target.setObjectName("tab_target")
        self.tab_con = QtWidgets.QWidget()
        self.tab_con.setObjectName("tab_con")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_con)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lay_h_con_ope = QtWidgets.QHBoxLayout()
        self.lay_h_con_ope.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_con_ope.setObjectName("lay_h_con_ope")
        self.lbl_con_uuid = QtWidgets.QLabel(self.tab_con)
        self.lbl_con_uuid.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_con_uuid.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_con_uuid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_con_uuid.setObjectName("lbl_con_uuid")
        self.lay_h_con_ope.addWidget(self.lbl_con_uuid)
        self.tbx_con_uuid = QtWidgets.QLineEdit(self.tab_con)
        self.tbx_con_uuid.setEnabled(False)
        self.tbx_con_uuid.setObjectName("tbx_con_uuid")
        self.lay_h_con_ope.addWidget(self.tbx_con_uuid)
        self.rad_con_new = QtWidgets.QRadioButton(self.tab_con)
        self.rad_con_new.setMinimumSize(QtCore.QSize(0, 0))
        self.rad_con_new.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rad_con_new.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rad_con_new.setObjectName("rad_con_new")
        self.lay_h_con_ope.addWidget(self.rad_con_new)
        self.rad_con_mod = QtWidgets.QRadioButton(self.tab_con)
        self.rad_con_mod.setObjectName("rad_con_mod")
        self.lay_h_con_ope.addWidget(self.rad_con_mod)
        self.gridLayout_2.addLayout(self.lay_h_con_ope, 0, 0, 1, 1)
        self.lay_h_con_ctrl = QtWidgets.QHBoxLayout()
        self.lay_h_con_ctrl.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_con_ctrl.setObjectName("lay_h_con_ctrl")
        self.btn_con_add = QtWidgets.QPushButton(self.tab_con)
        self.btn_con_add.setObjectName("btn_con_add")
        self.lay_h_con_ctrl.addWidget(self.btn_con_add)
        self.btn_con_update = QtWidgets.QPushButton(self.tab_con)
        self.btn_con_update.setObjectName("btn_con_update")
        self.lay_h_con_ctrl.addWidget(self.btn_con_update)
        self.btn_con_take = QtWidgets.QPushButton(self.tab_con)
        self.btn_con_take.setObjectName("btn_con_take")
        self.lay_h_con_ctrl.addWidget(self.btn_con_take)
        self.btn_con_imp = QtWidgets.QPushButton(self.tab_con)
        self.btn_con_imp.setObjectName("btn_con_imp")
        self.lay_h_con_ctrl.addWidget(self.btn_con_imp)
        self.btn_con_rec = QtWidgets.QPushButton(self.tab_con)
        self.btn_con_rec.setObjectName("btn_con_rec")
        self.lay_h_con_ctrl.addWidget(self.btn_con_rec)
        self.btn_con_del = QtWidgets.QPushButton(self.tab_con)
        self.btn_con_del.setObjectName("btn_con_del")
        self.lay_h_con_ctrl.addWidget(self.btn_con_del)
        self.gridLayout_2.addLayout(self.lay_h_con_ctrl, 5, 0, 1, 1)
        self.lay_h_con_tmp = QtWidgets.QHBoxLayout()
        self.lay_h_con_tmp.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_con_tmp.setObjectName("lay_h_con_tmp")
        self.lbl_con_tempral = QtWidgets.QLabel(self.tab_con)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_con_tempral.sizePolicy().hasHeightForWidth())
        self.lbl_con_tempral.setSizePolicy(sizePolicy)
        self.lbl_con_tempral.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_con_tempral.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_con_tempral.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_con_tempral.setObjectName("lbl_con_tempral")
        self.lay_h_con_tmp.addWidget(self.lbl_con_tempral)
        self.tbx_con_temporal = QtWidgets.QLineEdit(self.tab_con)
        self.tbx_con_temporal.setEnabled(False)
        self.tbx_con_temporal.setObjectName("tbx_con_temporal")
        self.lay_h_con_tmp.addWidget(self.tbx_con_temporal)
        self.gridLayout_2.addLayout(self.lay_h_con_tmp, 3, 0, 1, 1)
        self.lay_h_con_dsc = QtWidgets.QHBoxLayout()
        self.lay_h_con_dsc.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_con_dsc.setObjectName("lay_h_con_dsc")
        self.lbl_con_description = QtWidgets.QLabel(self.tab_con)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_con_description.sizePolicy().hasHeightForWidth())
        self.lbl_con_description.setSizePolicy(sizePolicy)
        self.lbl_con_description.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_con_description.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_con_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_con_description.setObjectName("lbl_con_description")
        self.lay_h_con_dsc.addWidget(self.lbl_con_description)
        self.tbx_con_description = QtWidgets.QLineEdit(self.tab_con)
        self.tbx_con_description.setEnabled(False)
        self.tbx_con_description.setObjectName("tbx_con_description")
        self.lay_h_con_dsc.addWidget(self.tbx_con_description)
        self.gridLayout_2.addLayout(self.lay_h_con_dsc, 4, 0, 1, 1)
        self.lay_h_con_nam = QtWidgets.QHBoxLayout()
        self.lay_h_con_nam.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_con_nam.setObjectName("lay_h_con_nam")
        self.lbl_con_name = QtWidgets.QLabel(self.tab_con)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_con_name.sizePolicy().hasHeightForWidth())
        self.lbl_con_name.setSizePolicy(sizePolicy)
        self.lbl_con_name.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_con_name.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_con_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_con_name.setObjectName("lbl_con_name")
        self.lay_h_con_nam.addWidget(self.lbl_con_name)
        self.tbx_con_name = QtWidgets.QLineEdit(self.tab_con)
        self.tbx_con_name.setEnabled(False)
        self.tbx_con_name.setObjectName("tbx_con_name")
        self.lay_h_con_nam.addWidget(self.tbx_con_name)
        self.gridLayout_2.addLayout(self.lay_h_con_nam, 1, 0, 1, 1)
        self.lay_h_con_geo = QtWidgets.QHBoxLayout()
        self.lay_h_con_geo.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_con_geo.setObjectName("lay_h_con_geo")
        self.lbl_con_geoname = QtWidgets.QLabel(self.tab_con)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_con_geoname.sizePolicy().hasHeightForWidth())
        self.lbl_con_geoname.setSizePolicy(sizePolicy)
        self.lbl_con_geoname.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_con_geoname.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_con_geoname.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_con_geoname.setObjectName("lbl_con_geoname")
        self.lay_h_con_geo.addWidget(self.lbl_con_geoname)
        self.tbx_con_geoname = QtWidgets.QLineEdit(self.tab_con)
        self.tbx_con_geoname.setEnabled(False)
        self.tbx_con_geoname.setObjectName("tbx_con_geoname")
        self.lay_h_con_geo.addWidget(self.tbx_con_geoname)
        self.gridLayout_2.addLayout(self.lay_h_con_geo, 2, 0, 1, 1)
        self.tab_target.addTab(self.tab_con, "")
        self.tab_mat = QtWidgets.QWidget()
        self.tab_mat.setObjectName("tab_mat")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_mat)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_mat_uuid = QtWidgets.QLabel(self.tab_mat)
        self.lbl_mat_uuid.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_mat_uuid.setMaximumSize(QtCore.QSize(100, 25))
        self.lbl_mat_uuid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_uuid.setObjectName("lbl_mat_uuid")
        self.horizontalLayout_5.addWidget(self.lbl_mat_uuid)
        self.tbx_mat_uuid = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_uuid.setEnabled(False)
        self.tbx_mat_uuid.setObjectName("tbx_mat_uuid")
        self.horizontalLayout_5.addWidget(self.tbx_mat_uuid)
        self.rad_mat_new = QtWidgets.QRadioButton(self.tab_mat)
        self.rad_mat_new.setMinimumSize(QtCore.QSize(0, 0))
        self.rad_mat_new.setMaximumSize(QtCore.QSize(200, 25))
        self.rad_mat_new.setObjectName("rad_mat_new")
        self.horizontalLayout_5.addWidget(self.rad_mat_new)
        self.rad_mat_mod = QtWidgets.QRadioButton(self.tab_mat)
        self.rad_mat_mod.setMaximumSize(QtCore.QSize(16777215, 25))
        self.rad_mat_mod.setObjectName("rad_mat_mod")
        self.horizontalLayout_5.addWidget(self.rad_mat_mod)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.lay_h_con_nam_3 = QtWidgets.QHBoxLayout()
        self.lay_h_con_nam_3.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_con_nam_3.setObjectName("lay_h_con_nam_3")
        self.lbl_mat_number = QtWidgets.QLabel(self.tab_mat)
        self.lbl_mat_number.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_mat_number.setMaximumSize(QtCore.QSize(100, 25))
        self.lbl_mat_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_number.setObjectName("lbl_mat_number")
        self.lay_h_con_nam_3.addWidget(self.lbl_mat_number)
        self.tbx_mat_number = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_number.setEnabled(False)
        self.tbx_mat_number.setObjectName("tbx_mat_number")
        self.lay_h_con_nam_3.addWidget(self.tbx_mat_number)
        self.lbl_mat_name = QtWidgets.QLabel(self.tab_mat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_mat_name.sizePolicy().hasHeightForWidth())
        self.lbl_mat_name.setSizePolicy(sizePolicy)
        self.lbl_mat_name.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_mat_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_name.setObjectName("lbl_mat_name")
        self.lay_h_con_nam_3.addWidget(self.lbl_mat_name)
        self.tbx_mat_name = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_name.setEnabled(False)
        self.tbx_mat_name.setObjectName("tbx_mat_name")
        self.lay_h_con_nam_3.addWidget(self.tbx_mat_name)
        self.verticalLayout_3.addLayout(self.lay_h_con_nam_3)
        self.lay_h_mat_geo = QtWidgets.QHBoxLayout()
        self.lay_h_mat_geo.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_mat_geo.setObjectName("lay_h_mat_geo")
        self.lbl_mat_geoname = QtWidgets.QLabel(self.tab_mat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_mat_geoname.sizePolicy().hasHeightForWidth())
        self.lbl_mat_geoname.setSizePolicy(sizePolicy)
        self.lbl_mat_geoname.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_mat_geoname.setMaximumSize(QtCore.QSize(100, 25))
        self.lbl_mat_geoname.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_geoname.setObjectName("lbl_mat_geoname")
        self.lay_h_mat_geo.addWidget(self.lbl_mat_geoname)
        self.tbx_mat_geo_lat = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_geo_lat.setEnabled(False)
        self.tbx_mat_geo_lat.setObjectName("tbx_mat_geo_lat")
        self.lay_h_mat_geo.addWidget(self.tbx_mat_geo_lat)
        self.lbl_mat_geo_lon = QtWidgets.QLabel(self.tab_mat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_mat_geo_lon.sizePolicy().hasHeightForWidth())
        self.lbl_mat_geo_lon.setSizePolicy(sizePolicy)
        self.lbl_mat_geo_lon.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_mat_geo_lon.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbl_mat_geo_lon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_geo_lon.setObjectName("lbl_mat_geo_lon")
        self.lay_h_mat_geo.addWidget(self.lbl_mat_geo_lon)
        self.tbx_mat_geo_lon = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_geo_lon.setEnabled(False)
        self.tbx_mat_geo_lon.setObjectName("tbx_mat_geo_lon")
        self.lay_h_mat_geo.addWidget(self.tbx_mat_geo_lon)
        self.lbl_mat_geo_alt = QtWidgets.QLabel(self.tab_mat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_mat_geo_alt.sizePolicy().hasHeightForWidth())
        self.lbl_mat_geo_alt.setSizePolicy(sizePolicy)
        self.lbl_mat_geo_alt.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_mat_geo_alt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbl_mat_geo_alt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_geo_alt.setObjectName("lbl_mat_geo_alt")
        self.lay_h_mat_geo.addWidget(self.lbl_mat_geo_alt)
        self.tbx_mat_geo_alt = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_geo_alt.setEnabled(False)
        self.tbx_mat_geo_alt.setObjectName("tbx_mat_geo_alt")
        self.lay_h_mat_geo.addWidget(self.tbx_mat_geo_alt)
        self.verticalLayout_3.addLayout(self.lay_h_mat_geo)
        self.lay_h_mat_tmp = QtWidgets.QHBoxLayout()
        self.lay_h_mat_tmp.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_mat_tmp.setObjectName("lay_h_mat_tmp")
        self.lbl_mat_tmp_bgn = QtWidgets.QLabel(self.tab_mat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_mat_tmp_bgn.sizePolicy().hasHeightForWidth())
        self.lbl_mat_tmp_bgn.setSizePolicy(sizePolicy)
        self.lbl_mat_tmp_bgn.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_mat_tmp_bgn.setMaximumSize(QtCore.QSize(100, 25))
        self.lbl_mat_tmp_bgn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_tmp_bgn.setObjectName("lbl_mat_tmp_bgn")
        self.lay_h_mat_tmp.addWidget(self.lbl_mat_tmp_bgn)
        self.tbx_mat_tmp_bgn = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_tmp_bgn.setEnabled(False)
        self.tbx_mat_tmp_bgn.setObjectName("tbx_mat_tmp_bgn")
        self.lay_h_mat_tmp.addWidget(self.tbx_mat_tmp_bgn)
        self.lbl_mat_tmp_mid = QtWidgets.QLabel(self.tab_mat)
        self.lbl_mat_tmp_mid.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_mat_tmp_mid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_tmp_mid.setObjectName("lbl_mat_tmp_mid")
        self.lay_h_mat_tmp.addWidget(self.lbl_mat_tmp_mid)
        self.tbx_mat_tmp_mid = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_tmp_mid.setEnabled(False)
        self.tbx_mat_tmp_mid.setObjectName("tbx_mat_tmp_mid")
        self.lay_h_mat_tmp.addWidget(self.tbx_mat_tmp_mid)
        self.lbl_mat_tmp_end = QtWidgets.QLabel(self.tab_mat)
        self.lbl_mat_tmp_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_tmp_end.setObjectName("lbl_mat_tmp_end")
        self.lay_h_mat_tmp.addWidget(self.lbl_mat_tmp_end)
        self.tbx_mat_tmp_end = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_tmp_end.setEnabled(False)
        self.tbx_mat_tmp_end.setObjectName("tbx_mat_tmp_end")
        self.lay_h_mat_tmp.addWidget(self.tbx_mat_tmp_end)
        self.verticalLayout_3.addLayout(self.lay_h_mat_tmp)
        self.lay_h_mat_dsc = QtWidgets.QHBoxLayout()
        self.lay_h_mat_dsc.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_mat_dsc.setObjectName("lay_h_mat_dsc")
        self.lbl_mat_description = QtWidgets.QLabel(self.tab_mat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_mat_description.sizePolicy().hasHeightForWidth())
        self.lbl_mat_description.setSizePolicy(sizePolicy)
        self.lbl_mat_description.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_mat_description.setMaximumSize(QtCore.QSize(100, 25))
        self.lbl_mat_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_description.setObjectName("lbl_mat_description")
        self.lay_h_mat_dsc.addWidget(self.lbl_mat_description)
        self.tbx_mat_description = QtWidgets.QLineEdit(self.tab_mat)
        self.tbx_mat_description.setEnabled(False)
        self.tbx_mat_description.setObjectName("tbx_mat_description")
        self.lay_h_mat_dsc.addWidget(self.tbx_mat_description)
        self.verticalLayout_3.addLayout(self.lay_h_mat_dsc)
        self.lay_h_mat_ctrl = QtWidgets.QHBoxLayout()
        self.lay_h_mat_ctrl.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_mat_ctrl.setObjectName("lay_h_mat_ctrl")
        self.btn_mat_add = QtWidgets.QPushButton(self.tab_mat)
        self.btn_mat_add.setObjectName("btn_mat_add")
        self.lay_h_mat_ctrl.addWidget(self.btn_mat_add)
        self.btn_mat_update = QtWidgets.QPushButton(self.tab_mat)
        self.btn_mat_update.setObjectName("btn_mat_update")
        self.lay_h_mat_ctrl.addWidget(self.btn_mat_update)
        self.btn_mat_take = QtWidgets.QPushButton(self.tab_mat)
        self.btn_mat_take.setObjectName("btn_mat_take")
        self.lay_h_mat_ctrl.addWidget(self.btn_mat_take)
        self.btn_mat_imp = QtWidgets.QPushButton(self.tab_mat)
        self.btn_mat_imp.setObjectName("btn_mat_imp")
        self.lay_h_mat_ctrl.addWidget(self.btn_mat_imp)
        self.btn_mat_rec = QtWidgets.QPushButton(self.tab_mat)
        self.btn_mat_rec.setObjectName("btn_mat_rec")
        self.lay_h_mat_ctrl.addWidget(self.btn_mat_rec)
        self.btn_mat_del = QtWidgets.QPushButton(self.tab_mat)
        self.btn_mat_del.setObjectName("btn_mat_del")
        self.lay_h_mat_ctrl.addWidget(self.btn_mat_del)
        self.verticalLayout_3.addLayout(self.lay_h_mat_ctrl)
        self.tab_target.addTab(self.tab_mat, "")
        self.gridLayout_3.addWidget(self.tab_target, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 450))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbx_fil_deleted = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbx_fil_deleted.setFont(font)
        self.cbx_fil_deleted.setChecked(True)
        self.cbx_fil_deleted.setObjectName("cbx_fil_deleted")
        self.horizontalLayout_6.addWidget(self.cbx_fil_deleted)
        self.cbx_fil_original = QtWidgets.QCheckBox(self.frame_4)
        self.cbx_fil_original.setChecked(True)
        self.cbx_fil_original.setObjectName("cbx_fil_original")
        self.horizontalLayout_6.addWidget(self.cbx_fil_original)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.tre_fls = QtWidgets.QTreeWidget(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tre_fls.setFont(font)
        self.tre_fls.setObjectName("tre_fls")
        self.tre_fls.header().setCascadingSectionResizes(True)
        self.tre_fls.header().setSortIndicatorShown(True)
        self.verticalLayout_5.addWidget(self.tre_fls)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.tab_img_info = QtWidgets.QTabWidget(self.frame_4)
        self.tab_img_info.setObjectName("tab_img_info")
        self.tab_img_preview = QtWidgets.QWidget()
        self.tab_img_preview.setObjectName("tab_img_preview")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_img_preview)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_img_preview = QtWidgets.QLabel(self.tab_img_preview)
        self.lbl_img_preview.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_img_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_img_preview.setObjectName("lbl_img_preview")
        self.horizontalLayout_4.addWidget(self.lbl_img_preview)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_img_rot_l = QtWidgets.QPushButton(self.tab_img_preview)
        self.btn_img_rot_l.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_img_rot_l.setText("")
        self.btn_img_rot_l.setCheckable(False)
        self.btn_img_rot_l.setObjectName("btn_img_rot_l")
        self.verticalLayout_4.addWidget(self.btn_img_rot_l)
        self.btn_img_rot_r = QtWidgets.QPushButton(self.tab_img_preview)
        self.btn_img_rot_r.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_img_rot_r.setText("")
        self.btn_img_rot_r.setCheckable(False)
        self.btn_img_rot_r.setObjectName("btn_img_rot_r")
        self.verticalLayout_4.addWidget(self.btn_img_rot_r)
        self.btn_img_rot_u = QtWidgets.QPushButton(self.tab_img_preview)
        self.btn_img_rot_u.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_img_rot_u.setText("")
        self.btn_img_rot_u.setCheckable(False)
        self.btn_img_rot_u.setObjectName("btn_img_rot_u")
        self.verticalLayout_4.addWidget(self.btn_img_rot_u)
        self.btn_img_enh = QtWidgets.QPushButton(self.tab_img_preview)
        self.btn_img_enh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_img_enh.setText("")
        self.btn_img_enh.setCheckable(False)
        self.btn_img_enh.setObjectName("btn_img_enh")
        self.verticalLayout_4.addWidget(self.btn_img_enh)
        self.btn_img_inv = QtWidgets.QPushButton(self.tab_img_preview)
        self.btn_img_inv.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_img_inv.setText("")
        self.btn_img_inv.setCheckable(False)
        self.btn_img_inv.setObjectName("btn_img_inv")
        self.verticalLayout_4.addWidget(self.btn_img_inv)
        self.btn_img_mno = QtWidgets.QPushButton(self.tab_img_preview)
        self.btn_img_mno.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_img_mno.setText("")
        self.btn_img_mno.setCheckable(False)
        self.btn_img_mno.setObjectName("btn_img_mno")
        self.verticalLayout_4.addWidget(self.btn_img_mno)
        self.btn_img_cnt = QtWidgets.QPushButton(self.tab_img_preview)
        self.btn_img_cnt.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_img_cnt.setText("")
        self.btn_img_cnt.setCheckable(False)
        self.btn_img_cnt.setObjectName("btn_img_cnt")
        self.verticalLayout_4.addWidget(self.btn_img_cnt)
        self.btn_img_sav = QtWidgets.QPushButton(self.tab_img_preview)
        self.btn_img_sav.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_img_sav.setText("")
        self.btn_img_sav.setCheckable(False)
        self.btn_img_sav.setObjectName("btn_img_sav")
        self.verticalLayout_4.addWidget(self.btn_img_sav)
        self.btn_img_del = QtWidgets.QPushButton(self.tab_img_preview)
        self.btn_img_del.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_img_del.setText("")
        self.btn_img_del.setIconSize(QtCore.QSize(24, 24))
        self.btn_img_del.setCheckable(False)
        self.btn_img_del.setObjectName("btn_img_del")
        self.verticalLayout_4.addWidget(self.btn_img_del)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, 2, -1, 2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cbx_fil_pub = QtWidgets.QCheckBox(self.tab_img_preview)
        self.cbx_fil_pub.setEnabled(True)
        self.cbx_fil_pub.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cbx_fil_pub.setObjectName("cbx_fil_pub")
        self.horizontalLayout_10.addWidget(self.cbx_fil_pub)
        self.cbx_fil_edit = QtWidgets.QCheckBox(self.tab_img_preview)
        self.cbx_fil_edit.setEnabled(True)
        self.cbx_fil_edit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cbx_fil_edit.setObjectName("cbx_fil_edit")
        self.horizontalLayout_10.addWidget(self.cbx_fil_edit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lbl_fil_capt = QtWidgets.QLabel(self.tab_img_preview)
        self.lbl_fil_capt.setMinimumSize(QtCore.QSize(110, 25))
        self.lbl_fil_capt.setMaximumSize(QtCore.QSize(100, 25))
        self.lbl_fil_capt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_fil_capt.setObjectName("lbl_fil_capt")
        self.horizontalLayout_11.addWidget(self.lbl_fil_capt)
        self.tbx_fil_capt = QtWidgets.QLineEdit(self.tab_img_preview)
        self.tbx_fil_capt.setEnabled(False)
        self.tbx_fil_capt.setMinimumSize(QtCore.QSize(0, 0))
        self.tbx_fil_capt.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tbx_fil_capt.setObjectName("tbx_fil_capt")
        self.horizontalLayout_11.addWidget(self.tbx_fil_capt)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbl_fil_stts = QtWidgets.QLabel(self.tab_img_preview)
        self.lbl_fil_stts.setMinimumSize(QtCore.QSize(110, 0))
        self.lbl_fil_stts.setMaximumSize(QtCore.QSize(100, 25))
        self.lbl_fil_stts.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_fil_stts.setObjectName("lbl_fil_stts")
        self.horizontalLayout_8.addWidget(self.lbl_fil_stts)
        self.tbx_fil_stts = QtWidgets.QLineEdit(self.tab_img_preview)
        self.tbx_fil_stts.setEnabled(False)
        self.tbx_fil_stts.setObjectName("tbx_fil_stts")
        self.horizontalLayout_8.addWidget(self.tbx_fil_stts)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_fil_eope = QtWidgets.QLabel(self.tab_img_preview)
        self.lbl_fil_eope.setMinimumSize(QtCore.QSize(110, 25))
        self.lbl_fil_eope.setMaximumSize(QtCore.QSize(100, 25))
        self.lbl_fil_eope.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_fil_eope.setObjectName("lbl_fil_eope")
        self.horizontalLayout_7.addWidget(self.lbl_fil_eope)
        self.tbx_fil_eope = QtWidgets.QLineEdit(self.tab_img_preview)
        self.tbx_fil_eope.setEnabled(False)
        self.tbx_fil_eope.setObjectName("tbx_fil_eope")
        self.horizontalLayout_7.addWidget(self.tbx_fil_eope)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.tab_src = QtWidgets.QTabWidget(self.tab_img_preview)
        self.tab_src.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_src.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_src.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_src.setIconSize(QtCore.QSize(24, 24))
        self.tab_src.setElideMode(QtCore.Qt.ElideNone)
        self.tab_src.setDocumentMode(False)
        self.tab_src.setTabsClosable(False)
        self.tab_src.setTabBarAutoHide(False)
        self.tab_src.setObjectName("tab_src")
        self.tab_src_img = QtWidgets.QWidget()
        self.tab_src_img.setObjectName("tab_src_img")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_src_img)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn_open_gimp = QtWidgets.QPushButton(self.tab_src_img)
        self.btn_open_gimp.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_open_gimp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_open_gimp.setObjectName("btn_open_gimp")
        self.horizontalLayout_9.addWidget(self.btn_open_gimp)
        self.tab_src.addTab(self.tab_src_img, "")
        self.tab_src_snd = QtWidgets.QWidget()
        self.tab_src_snd.setObjectName("tab_src_snd")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_src_snd)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.btn_snd_play = QtWidgets.QPushButton(self.tab_src_snd)
        self.btn_snd_play.setObjectName("btn_snd_play")
        self.horizontalLayout_12.addWidget(self.btn_snd_play)
        self.btn_snd_stop = QtWidgets.QPushButton(self.tab_src_snd)
        self.btn_snd_stop.setObjectName("btn_snd_stop")
        self.horizontalLayout_12.addWidget(self.btn_snd_stop)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.tab_src.addTab(self.tab_src_snd, "")
        self.verticalLayout_9.addWidget(self.tab_src)
        self.verticalLayout_6.addLayout(self.verticalLayout_9)
        self.tab_img_info.addTab(self.tab_img_preview, "")
        self.tab_img_prop = QtWidgets.QWidget()
        self.tab_img_prop.setObjectName("tab_img_prop")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_img_prop)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tre_img_prop = QtWidgets.QTreeWidget(self.tab_img_prop)
        self.tre_img_prop.setObjectName("tre_img_prop")
        self.tre_img_prop.header().setDefaultSectionSize(100)
        self.horizontalLayout_3.addWidget(self.tre_img_prop)
        self.tab_img_info.addTab(self.tab_img_prop, "")
        self.horizontalLayout_2.addWidget(self.tab_img_info)
        self.gridLayout_3.addWidget(self.frame_4, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.lay_v_item_info = QtWidgets.QVBoxLayout()
        self.lay_v_item_info.setContentsMargins(-1, 0, -1, -1)
        self.lay_v_item_info.setObjectName("lay_v_item_info")
        self.horizontalLayout.addLayout(self.lay_v_item_info)
        MainWindow.setCentralWidget(self.centralwidget)
        self.bar_menu = QtWidgets.QMenuBar(MainWindow)
        self.bar_menu.setGeometry(QtCore.QRect(0, 0, 1400, 23))
        self.bar_menu.setObjectName("bar_menu")
        self.men_prj = QtWidgets.QMenu(self.bar_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.men_prj.sizePolicy().hasHeightForWidth())
        self.men_prj.setSizePolicy(sizePolicy)
        self.men_prj.setMinimumSize(QtCore.QSize(0, 0))
        self.men_prj.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.men_prj.setObjectName("men_prj")
        self.mem_prj_exp = QtWidgets.QMenu(self.men_prj)
        self.mem_prj_exp.setObjectName("mem_prj_exp")
        MainWindow.setMenuBar(self.bar_menu)
        self.actionCreate_New_Project = QtWidgets.QAction(MainWindow)
        self.actionCreate_New_Project.setObjectName("actionCreate_New_Project")
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.act_prj_open = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.act_prj_open.setFont(font)
        self.act_prj_open.setIconVisibleInMenu(True)
        self.act_prj_open.setObjectName("act_prj_open")
        self.act_imp_db = QtWidgets.QAction(MainWindow)
        self.act_imp_db.setObjectName("act_imp_db")
        self.act_imp_txt = QtWidgets.QAction(MainWindow)
        self.act_imp_txt.setObjectName("act_imp_txt")
        self.act_imp_fls = QtWidgets.QAction(MainWindow)
        self.act_imp_fls.setObjectName("act_imp_fls")
        self.act_export_html = QtWidgets.QAction(MainWindow)
        self.act_export_html.setObjectName("act_export_html")
        self.mem_prj_exp.addAction(self.act_export_html)
        self.men_prj.addAction(self.act_prj_open)
        self.men_prj.addAction(self.mem_prj_exp.menuAction())
        self.bar_menu.addAction(self.men_prj.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_control.setCurrentIndex(0)
        self.tab_target.setCurrentIndex(0)
        self.tab_img_info.setCurrentIndex(0)
        self.tab_src.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tab_control, self.tre_prj_item)
        MainWindow.setTabOrder(self.tre_prj_item, self.btn_cam_detect)
        MainWindow.setTabOrder(self.btn_cam_detect, self.cbx_cam_size)
        MainWindow.setTabOrder(self.cbx_cam_size, self.cbx_cam_iso)
        MainWindow.setTabOrder(self.cbx_cam_iso, self.cbx_cam_wht)
        MainWindow.setTabOrder(self.cbx_cam_wht, self.cbx_cam_exp)
        MainWindow.setTabOrder(self.cbx_cam_exp, self.cbx_cam_fval)
        MainWindow.setTabOrder(self.cbx_cam_fval, self.cbx_cam_qoi)
        MainWindow.setTabOrder(self.cbx_cam_qoi, self.cbx_cam_fmod)
        MainWindow.setTabOrder(self.cbx_cam_fmod, self.cbx_cam_epg)
        MainWindow.setTabOrder(self.cbx_cam_epg, self.cbx_cam_cpt)
        MainWindow.setTabOrder(self.cbx_cam_cpt, self.cbx_cam_met)
        MainWindow.setTabOrder(self.cbx_cam_met, self.tab_target)
        MainWindow.setTabOrder(self.tab_target, self.tbx_con_uuid)
        MainWindow.setTabOrder(self.tbx_con_uuid, self.rad_con_new)
        MainWindow.setTabOrder(self.rad_con_new, self.rad_con_mod)
        MainWindow.setTabOrder(self.rad_con_mod, self.tbx_con_name)
        MainWindow.setTabOrder(self.tbx_con_name, self.tbx_con_geoname)
        MainWindow.setTabOrder(self.tbx_con_geoname, self.tbx_con_temporal)
        MainWindow.setTabOrder(self.tbx_con_temporal, self.tbx_con_description)
        MainWindow.setTabOrder(self.tbx_con_description, self.btn_con_add)
        MainWindow.setTabOrder(self.btn_con_add, self.btn_con_update)
        MainWindow.setTabOrder(self.btn_con_update, self.btn_con_take)
        MainWindow.setTabOrder(self.btn_con_take, self.btn_con_rec)
        MainWindow.setTabOrder(self.btn_con_rec, self.btn_con_del)
        MainWindow.setTabOrder(self.btn_con_del, self.tbx_mat_uuid)
        MainWindow.setTabOrder(self.tbx_mat_uuid, self.rad_mat_new)
        MainWindow.setTabOrder(self.rad_mat_new, self.rad_mat_mod)
        MainWindow.setTabOrder(self.rad_mat_mod, self.tbx_mat_number)
        MainWindow.setTabOrder(self.tbx_mat_number, self.tbx_mat_name)
        MainWindow.setTabOrder(self.tbx_mat_name, self.tbx_mat_geo_lat)
        MainWindow.setTabOrder(self.tbx_mat_geo_lat, self.tbx_mat_geo_lon)
        MainWindow.setTabOrder(self.tbx_mat_geo_lon, self.tbx_mat_geo_alt)
        MainWindow.setTabOrder(self.tbx_mat_geo_alt, self.tbx_mat_tmp_bgn)
        MainWindow.setTabOrder(self.tbx_mat_tmp_bgn, self.tbx_mat_tmp_mid)
        MainWindow.setTabOrder(self.tbx_mat_tmp_mid, self.tbx_mat_tmp_end)
        MainWindow.setTabOrder(self.tbx_mat_tmp_end, self.tbx_mat_description)
        MainWindow.setTabOrder(self.tbx_mat_description, self.btn_mat_add)
        MainWindow.setTabOrder(self.btn_mat_add, self.btn_mat_update)
        MainWindow.setTabOrder(self.btn_mat_update, self.btn_mat_take)
        MainWindow.setTabOrder(self.btn_mat_take, self.btn_mat_rec)
        MainWindow.setTabOrder(self.btn_mat_rec, self.btn_mat_del)
        MainWindow.setTabOrder(self.btn_mat_del, self.cbx_fil_deleted)
        MainWindow.setTabOrder(self.cbx_fil_deleted, self.cbx_fil_original)
        MainWindow.setTabOrder(self.cbx_fil_original, self.tre_fls)
        MainWindow.setTabOrder(self.tre_fls, self.tab_img_info)
        MainWindow.setTabOrder(self.tab_img_info, self.btn_img_rot_l)
        MainWindow.setTabOrder(self.btn_img_rot_l, self.btn_img_rot_r)
        MainWindow.setTabOrder(self.btn_img_rot_r, self.btn_img_rot_u)
        MainWindow.setTabOrder(self.btn_img_rot_u, self.btn_img_enh)
        MainWindow.setTabOrder(self.btn_img_enh, self.btn_img_inv)
        MainWindow.setTabOrder(self.btn_img_inv, self.btn_img_mno)
        MainWindow.setTabOrder(self.btn_img_mno, self.btn_img_cnt)
        MainWindow.setTabOrder(self.btn_img_cnt, self.btn_img_sav)
        MainWindow.setTabOrder(self.btn_img_sav, self.btn_img_del)
        MainWindow.setTabOrder(self.btn_img_del, self.cbx_fil_pub)
        MainWindow.setTabOrder(self.cbx_fil_pub, self.cbx_fil_edit)
        MainWindow.setTabOrder(self.cbx_fil_edit, self.tbx_fil_capt)
        MainWindow.setTabOrder(self.tbx_fil_capt, self.tbx_fil_stts)
        MainWindow.setTabOrder(self.tbx_fil_stts, self.tbx_fil_eope)
        MainWindow.setTabOrder(self.tbx_fil_eope, self.tab_src)
        MainWindow.setTabOrder(self.tab_src, self.btn_snd_play)
        MainWindow.setTabOrder(self.btn_snd_play, self.btn_snd_stop)
        MainWindow.setTabOrder(self.btn_snd_stop, self.btn_open_gimp)
        MainWindow.setTabOrder(self.btn_open_gimp, self.tre_img_prop)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SurveyDataManager"))
        self.lbl_prjDir.setText(_translate("MainWindow", "プロジェクト : "))
        self.tre_prj_item.headerItem().setText(0, _translate("MainWindow", "UUID"))
        self.tre_prj_item.headerItem().setText(1, _translate("MainWindow", "名称"))
        self.tab_control.setTabText(self.tab_control.indexOf(self.tab_prj_item), _translate("MainWindow", "アイテム"))
        self.lbl_cam_detected.setText(_translate("MainWindow", "接続中のカメラ: No Camera detected"))
        self.btn_cam_detect.setText(_translate("MainWindow", "カメラの認識"))
        self.grp_cam.setTitle(_translate("MainWindow", "撮影モード"))
        self.lbl_cam_qoi.setText(_translate("MainWindow", "Image Quality"))
        self.lbl_cam_fmod.setText(_translate("MainWindow", "Focus Mode"))
        self.lbl_cam_epg.setText(_translate("MainWindow", "Exposure Program"))
        self.lbl_cam_size.setText(_translate("MainWindow", "Image Size"))
        self.lbl_cam_iso.setText(_translate("MainWindow", "ISO Speed Rating"))
        self.lbl_cam_cpt.setText(_translate("MainWindow", "Capture Mode"))
        self.lbl_cam_fval.setText(_translate("MainWindow", "F-Number"))
        self.lbl_cam_wht.setText(_translate("MainWindow", "White Balance"))
        self.lbl_cam_exp.setText(_translate("MainWindow", "Exposure Compensation"))
        self.lbl_cam_met.setText(_translate("MainWindow", "Metering Mode"))
        self.tab_control.setTabText(self.tab_control.indexOf(self.tab_prj_cam), _translate("MainWindow", "カメラ"))
        self.lbl_con_uuid.setText(_translate("MainWindow", "UUID"))
        self.rad_con_new.setText(_translate("MainWindow", "新規作成"))
        self.rad_con_mod.setText(_translate("MainWindow", "情報更新"))
        self.btn_con_add.setText(_translate("MainWindow", "統合体の追加"))
        self.btn_con_update.setText(_translate("MainWindow", "統合体の更新"))
        self.btn_con_take.setText(_translate("MainWindow", "撮影する"))
        self.btn_con_imp.setText(_translate("MainWindow", " インポートする"))
        self.btn_con_rec.setText(_translate("MainWindow", "録音する"))
        self.btn_con_del.setText(_translate("MainWindow", "統合体の削除"))
        self.lbl_con_tempral.setText(_translate("MainWindow", "時間識別子"))
        self.lbl_con_description.setText(_translate("MainWindow", "統合体の備考"))
        self.lbl_con_name.setText(_translate("MainWindow", "統合体の名称"))
        self.lbl_con_geoname.setText(_translate("MainWindow", "地理識別子"))
        self.tab_target.setTabText(self.tab_target.indexOf(self.tab_con), _translate("MainWindow", "統合体情報"))
        self.lbl_mat_uuid.setText(_translate("MainWindow", "UUID"))
        self.rad_mat_new.setText(_translate("MainWindow", "新規作成"))
        self.rad_mat_mod.setText(_translate("MainWindow", "情報更新"))
        self.lbl_mat_number.setText(_translate("MainWindow", "資料番号"))
        self.lbl_mat_name.setText(_translate("MainWindow", "資料の名称"))
        self.lbl_mat_geoname.setText(_translate("MainWindow", "緯度"))
        self.lbl_mat_geo_lon.setText(_translate("MainWindow", "経度"))
        self.lbl_mat_geo_alt.setText(_translate("MainWindow", "標高"))
        self.lbl_mat_tmp_bgn.setText(_translate("MainWindow", "開始時期"))
        self.lbl_mat_tmp_mid.setText(_translate("MainWindow", "中間時期"))
        self.lbl_mat_tmp_end.setText(_translate("MainWindow", "終了時期"))
        self.lbl_mat_description.setText(_translate("MainWindow", "資料の備考"))
        self.btn_mat_add.setText(_translate("MainWindow", "資料の追加"))
        self.btn_mat_update.setText(_translate("MainWindow", "資料の更新"))
        self.btn_mat_take.setText(_translate("MainWindow", "撮影する"))
        self.btn_mat_imp.setText(_translate("MainWindow", " インポートする"))
        self.btn_mat_rec.setText(_translate("MainWindow", "録音する"))
        self.btn_mat_del.setText(_translate("MainWindow", "資料の削除"))
        self.tab_target.setTabText(self.tab_target.indexOf(self.tab_mat), _translate("MainWindow", "資料情報"))
        self.cbx_fil_deleted.setText(_translate("MainWindow", "削除済みを表示"))
        self.cbx_fil_original.setText(_translate("MainWindow", "オリジナルを表示"))
        self.tre_fls.headerItem().setText(0, _translate("MainWindow", "画像ID"))
        self.tre_fls.headerItem().setText(1, _translate("MainWindow", "名前"))
        self.tre_fls.headerItem().setText(2, _translate("MainWindow", "データタイプ"))
        self.lbl_img_preview.setText(_translate("MainWindow", "preview"))
        self.cbx_fil_pub.setText(_translate("MainWindow", "公開設定"))
        self.cbx_fil_edit.setText(_translate("MainWindow", "削除可能"))
        self.lbl_fil_capt.setText(_translate("MainWindow", "キャプション : "))
        self.lbl_fil_stts.setText(_translate("MainWindow", "ステータス : "))
        self.lbl_fil_eope.setText(_translate("MainWindow", "追加処理 : "))
        self.btn_open_gimp.setText(_translate("MainWindow", "GIMP"))
        self.tab_src.setTabText(self.tab_src.indexOf(self.tab_src_img), _translate("MainWindow", "画像"))
        self.btn_snd_play.setText(_translate("MainWindow", "Play"))
        self.btn_snd_stop.setText(_translate("MainWindow", "Stop"))
        self.tab_src.setTabText(self.tab_src.indexOf(self.tab_src_snd), _translate("MainWindow", "音声"))
        self.tab_img_info.setTabText(self.tab_img_info.indexOf(self.tab_img_preview), _translate("MainWindow", "プレビュー"))
        self.tre_img_prop.headerItem().setText(0, _translate("MainWindow", "プロパティ"))
        self.tre_img_prop.headerItem().setText(1, _translate("MainWindow", "値"))
        self.tab_img_info.setTabText(self.tab_img_info.indexOf(self.tab_img_prop), _translate("MainWindow", "プロパティ"))
        self.men_prj.setTitle(_translate("MainWindow", "プロジェクト"))
        self.mem_prj_exp.setTitle(_translate("MainWindow", "Export"))
        self.actionCreate_New_Project.setText(_translate("MainWindow", "Create New Project"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.act_prj_open.setText(_translate("MainWindow", "開く"))
        self.act_prj_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.act_imp_db.setText(_translate("MainWindow", "データベース"))
        self.act_imp_txt.setText(_translate("MainWindow", "テキストデータ"))
        self.act_imp_fls.setText(_translate("MainWindow", "ファイルシステム"))
        self.act_export_html.setText(_translate("MainWindow", "Export as HTML"))

