# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yufujimoto/git/SurveyDataCollector/ui/cameraSelectDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraSelectDialog(object):
    def setupUi(self, CameraSelectDialog):
        CameraSelectDialog.setObjectName("CameraSelectDialog")
        CameraSelectDialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(CameraSelectDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tre_cam = QtWidgets.QTreeWidget(CameraSelectDialog)
        self.tre_cam.setObjectName("tre_cam")
        self.gridLayout.addWidget(self.tre_cam, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(CameraSelectDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(CameraSelectDialog)
        self.buttonBox.accepted.connect(CameraSelectDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(CameraSelectDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CameraSelectDialog)

    def retranslateUi(self, CameraSelectDialog):
        _translate = QtCore.QCoreApplication.translate
        CameraSelectDialog.setWindowTitle(_translate("CameraSelectDialog", "Dialog"))
        self.tre_cam.headerItem().setText(0, _translate("CameraSelectDialog", "port"))
        self.tre_cam.headerItem().setText(1, _translate("CameraSelectDialog", "name"))
