# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yufujimoto/GitHub/SurveyDataCollector/ui/imageInformationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_imageInformationDialog(object):
    def setupUi(self, imageInformationDialog):
        imageInformationDialog.setObjectName("imageInformationDialog")
        imageInformationDialog.resize(849, 768)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(imageInformationDialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lay_v_info = QtWidgets.QVBoxLayout()
        self.lay_v_info.setContentsMargins(-1, 0, -1, -1)
        self.lay_v_info.setSpacing(6)
        self.lay_v_info.setObjectName("lay_v_info")
        self.lay_h_setting = QtWidgets.QHBoxLayout()
        self.lay_h_setting.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_setting.setObjectName("lay_h_setting")
        self.cbx_fil_pub = QtWidgets.QCheckBox(imageInformationDialog)
        self.cbx_fil_pub.setObjectName("cbx_fil_pub")
        self.lay_h_setting.addWidget(self.cbx_fil_pub)
        self.cbx_fil_edit = QtWidgets.QCheckBox(imageInformationDialog)
        self.cbx_fil_edit.setObjectName("cbx_fil_edit")
        self.lay_h_setting.addWidget(self.cbx_fil_edit)
        self.lab_fil_sta = QtWidgets.QLabel(imageInformationDialog)
        self.lab_fil_sta.setMinimumSize(QtCore.QSize(110, 0))
        self.lab_fil_sta.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lab_fil_sta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_fil_sta.setObjectName("lab_fil_sta")
        self.lay_h_setting.addWidget(self.lab_fil_sta)
        self.cmb_fil_stts = QtWidgets.QComboBox(imageInformationDialog)
        self.cmb_fil_stts.setMinimumSize(QtCore.QSize(200, 0))
        self.cmb_fil_stts.setObjectName("cmb_fil_stts")
        self.lay_h_setting.addWidget(self.cmb_fil_stts)
        self.lay_v_info.addLayout(self.lay_h_setting)
        self.lay_h_alias = QtWidgets.QHBoxLayout()
        self.lay_h_alias.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_alias.setObjectName("lay_h_alias")
        self.lab_fil_ali = QtWidgets.QLabel(imageInformationDialog)
        self.lab_fil_ali.setMinimumSize(QtCore.QSize(110, 0))
        self.lab_fil_ali.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lab_fil_ali.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_fil_ali.setObjectName("lab_fil_ali")
        self.lay_h_alias.addWidget(self.lab_fil_ali)
        self.tbx_fil_ali = QtWidgets.QLineEdit(imageInformationDialog)
        self.tbx_fil_ali.setObjectName("tbx_fil_ali")
        self.lay_h_alias.addWidget(self.tbx_fil_ali)
        self.lay_v_info.addLayout(self.lay_h_alias)
        self.lay_h_date = QtWidgets.QHBoxLayout()
        self.lay_h_date.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_date.setObjectName("lay_h_date")
        self.lab_fil_dt_cr = QtWidgets.QLabel(imageInformationDialog)
        self.lab_fil_dt_cr.setMinimumSize(QtCore.QSize(110, 0))
        self.lab_fil_dt_cr.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lab_fil_dt_cr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_fil_dt_cr.setObjectName("lab_fil_dt_cr")
        self.lay_h_date.addWidget(self.lab_fil_dt_cr)
        self.dte_fil_dt_cre = QtWidgets.QDateTimeEdit(imageInformationDialog)
        self.dte_fil_dt_cre.setMinimumSize(QtCore.QSize(200, 0))
        self.dte_fil_dt_cre.setObjectName("dte_fil_dt_cre")
        self.lay_h_date.addWidget(self.dte_fil_dt_cre)
        self.btn_fil_dt_cre_exif = QtWidgets.QPushButton(imageInformationDialog)
        self.btn_fil_dt_cre_exif.setFlat(True)
        self.btn_fil_dt_cre_exif.setObjectName("btn_fil_dt_cre_exif")
        self.lay_h_date.addWidget(self.btn_fil_dt_cre_exif)
        self.lab_fil_dt_mod = QtWidgets.QLabel(imageInformationDialog)
        self.lab_fil_dt_mod.setMinimumSize(QtCore.QSize(110, 0))
        self.lab_fil_dt_mod.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lab_fil_dt_mod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_fil_dt_mod.setObjectName("lab_fil_dt_mod")
        self.lay_h_date.addWidget(self.lab_fil_dt_mod)
        self.dte_fil_dt_mod = QtWidgets.QDateTimeEdit(imageInformationDialog)
        self.dte_fil_dt_mod.setMinimumSize(QtCore.QSize(200, 0))
        self.dte_fil_dt_mod.setObjectName("dte_fil_dt_mod")
        self.lay_h_date.addWidget(self.dte_fil_dt_mod)
        self.btn_fil_dt_mod_exif = QtWidgets.QPushButton(imageInformationDialog)
        self.btn_fil_dt_mod_exif.setFlat(True)
        self.btn_fil_dt_mod_exif.setObjectName("btn_fil_dt_mod_exif")
        self.lay_h_date.addWidget(self.btn_fil_dt_mod_exif)
        self.lay_v_info.addLayout(self.lay_h_date)
        self.lay_h_operation = QtWidgets.QHBoxLayout()
        self.lay_h_operation.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_operation.setObjectName("lay_h_operation")
        self.lab_fil_ope = QtWidgets.QLabel(imageInformationDialog)
        self.lab_fil_ope.setMinimumSize(QtCore.QSize(110, 0))
        self.lab_fil_ope.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lab_fil_ope.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_fil_ope.setObjectName("lab_fil_ope")
        self.lay_h_operation.addWidget(self.lab_fil_ope)
        self.cmb_fil_eope = QtWidgets.QComboBox(imageInformationDialog)
        self.cmb_fil_eope.setMinimumSize(QtCore.QSize(200, 0))
        self.cmb_fil_eope.setObjectName("cmb_fil_eope")
        self.lay_h_operation.addWidget(self.cmb_fil_eope)
        self.lab_fil_ope_app = QtWidgets.QLabel(imageInformationDialog)
        self.lab_fil_ope_app.setMinimumSize(QtCore.QSize(110, 0))
        self.lab_fil_ope_app.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_fil_ope_app.setObjectName("lab_fil_ope_app")
        self.lay_h_operation.addWidget(self.lab_fil_ope_app)
        self.tbx_fil_ope_app = QtWidgets.QLineEdit(imageInformationDialog)
        self.tbx_fil_ope_app.setObjectName("tbx_fil_ope_app")
        self.lay_h_operation.addWidget(self.tbx_fil_ope_app)
        self.lay_v_info.addLayout(self.lay_h_operation)
        self.lay_h_caption = QtWidgets.QHBoxLayout()
        self.lay_h_caption.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_caption.setObjectName("lay_h_caption")
        self.lab_fil_cap = QtWidgets.QLabel(imageInformationDialog)
        self.lab_fil_cap.setMinimumSize(QtCore.QSize(110, 0))
        self.lab_fil_cap.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lab_fil_cap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lab_fil_cap.setObjectName("lab_fil_cap")
        self.lay_h_caption.addWidget(self.lab_fil_cap)
        self.tbx_fil_capt = QtWidgets.QLineEdit(imageInformationDialog)
        self.tbx_fil_capt.setObjectName("tbx_fil_capt")
        self.lay_h_caption.addWidget(self.tbx_fil_capt)
        self.lay_v_info.addLayout(self.lay_h_caption)
        self.lay_h_description = QtWidgets.QHBoxLayout()
        self.lay_h_description.setContentsMargins(-1, 0, -1, -1)
        self.lay_h_description.setObjectName("lay_h_description")
        self.lbl_fil_dsc = QtWidgets.QLabel(imageInformationDialog)
        self.lbl_fil_dsc.setMinimumSize(QtCore.QSize(110, 0))
        self.lbl_fil_dsc.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lbl_fil_dsc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_fil_dsc.setObjectName("lbl_fil_dsc")
        self.lay_h_description.addWidget(self.lbl_fil_dsc)
        self.tbx_fil_dsc = QtWidgets.QLineEdit(imageInformationDialog)
        self.tbx_fil_dsc.setObjectName("tbx_fil_dsc")
        self.lay_h_description.addWidget(self.tbx_fil_dsc)
        self.lay_v_info.addLayout(self.lay_h_description)
        self.verticalLayout_2.addLayout(self.lay_v_info)
        self.tab_src = QtWidgets.QTabWidget(imageInformationDialog)
        self.tab_src.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_src.setObjectName("tab_src")
        self.verticalLayout_2.addWidget(self.tab_src)
        self.laly_h_update = QtWidgets.QHBoxLayout()
        self.laly_h_update.setContentsMargins(-1, 10, -1, 10)
        self.laly_h_update.setObjectName("laly_h_update")
        self.btn_fil_update = QtWidgets.QPushButton(imageInformationDialog)
        self.btn_fil_update.setFlat(True)
        self.btn_fil_update.setObjectName("btn_fil_update")
        self.laly_h_update.addWidget(self.btn_fil_update)
        self.verticalLayout_2.addLayout(self.laly_h_update)
        self.box_fil_ope = QtWidgets.QDialogButtonBox(imageInformationDialog)
        self.box_fil_ope.setOrientation(QtCore.Qt.Horizontal)
        self.box_fil_ope.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.box_fil_ope.setObjectName("box_fil_ope")
        self.verticalLayout_2.addWidget(self.box_fil_ope)

        self.retranslateUi(imageInformationDialog)
        self.tab_src.setCurrentIndex(-1)
        self.box_fil_ope.accepted.connect(imageInformationDialog.accept)
        self.box_fil_ope.rejected.connect(imageInformationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(imageInformationDialog)

    def retranslateUi(self, imageInformationDialog):
        _translate = QtCore.QCoreApplication.translate
        imageInformationDialog.setWindowTitle(_translate("imageInformationDialog", "Dialog"))
        self.cbx_fil_pub.setText(_translate("imageInformationDialog", "公開設定"))
        self.cbx_fil_edit.setText(_translate("imageInformationDialog", "削除可能"))
        self.lab_fil_sta.setText(_translate("imageInformationDialog", "ステータス："))
        self.lab_fil_ali.setText(_translate("imageInformationDialog", "別　　名："))
        self.lab_fil_dt_cr.setText(_translate("imageInformationDialog", "作成日時："))
        self.dte_fil_dt_cre.setDisplayFormat(_translate("imageInformationDialog", "yyyy-MM-dd HH:mm:zz"))
        self.btn_fil_dt_cre_exif.setText(_translate("imageInformationDialog", "Exifから取得"))
        self.lab_fil_dt_mod.setText(_translate("imageInformationDialog", "編集日時："))
        self.dte_fil_dt_mod.setDisplayFormat(_translate("imageInformationDialog", "yyyy-MM-dd HH:mm:zz"))
        self.btn_fil_dt_mod_exif.setText(_translate("imageInformationDialog", "Exifから取得"))
        self.lab_fil_ope.setText(_translate("imageInformationDialog", "操　　作："))
        self.lab_fil_ope_app.setText(_translate("imageInformationDialog", "操作アプリ："))
        self.lab_fil_cap.setText(_translate("imageInformationDialog", "キャプション："))
        self.lbl_fil_dsc.setText(_translate("imageInformationDialog", "備　　考："))
        self.btn_fil_update.setText(_translate("imageInformationDialog", "更新する"))

