# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yufujimoto/GitHub/SurveyDataCollector/ui/material.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_materialDialog(object):
    def setupUi(self, materialDialog):
        materialDialog.setObjectName("materialDialog")
        materialDialog.resize(761, 476)
        self.gridLayout = QtWidgets.QGridLayout(materialDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_mat_tmp_bgn = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_tmp_bgn.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_tmp_bgn.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_tmp_bgn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_tmp_bgn.setObjectName("lbl_mat_tmp_bgn")
        self.horizontalLayout_4.addWidget(self.lbl_mat_tmp_bgn)
        self.tbx_mat_tmp_bgn = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_tmp_bgn.setObjectName("tbx_mat_tmp_bgn")
        self.horizontalLayout_4.addWidget(self.tbx_mat_tmp_bgn)
        self.lbl_mat_tmp_mid = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_tmp_mid.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_tmp_mid.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_tmp_mid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_tmp_mid.setObjectName("lbl_mat_tmp_mid")
        self.horizontalLayout_4.addWidget(self.lbl_mat_tmp_mid)
        self.tbx_mat_tmp_mid = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_tmp_mid.setObjectName("tbx_mat_tmp_mid")
        self.horizontalLayout_4.addWidget(self.tbx_mat_tmp_mid)
        self.lbl_mat_tmp_end = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_tmp_end.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_tmp_end.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_tmp_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_tmp_end.setObjectName("lbl_mat_tmp_end")
        self.horizontalLayout_4.addWidget(self.lbl_mat_tmp_end)
        self.tbx_mat_tmp_end = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_tmp_end.setObjectName("tbx_mat_tmp_end")
        self.horizontalLayout_4.addWidget(self.tbx_mat_tmp_end)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_mat_description = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_description.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_description.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_description.setObjectName("lbl_mat_description")
        self.horizontalLayout_5.addWidget(self.lbl_mat_description)
        self.tbx_mat_description = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_description.setObjectName("tbx_mat_description")
        self.horizontalLayout_5.addWidget(self.tbx_mat_description)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_mat_geo_lat = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_geo_lat.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_geo_lat.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_geo_lat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_geo_lat.setObjectName("lbl_mat_geo_lat")
        self.horizontalLayout_3.addWidget(self.lbl_mat_geo_lat)
        self.tbx_mat_geo_lat = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_geo_lat.setObjectName("tbx_mat_geo_lat")
        self.horizontalLayout_3.addWidget(self.tbx_mat_geo_lat)
        self.lbl_mat_geo_lon = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_geo_lon.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_geo_lon.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_geo_lon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_geo_lon.setObjectName("lbl_mat_geo_lon")
        self.horizontalLayout_3.addWidget(self.lbl_mat_geo_lon)
        self.tbx_mat_geo_lon = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_geo_lon.setObjectName("tbx_mat_geo_lon")
        self.horizontalLayout_3.addWidget(self.tbx_mat_geo_lon)
        self.lbl_mat_geo_alt = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_geo_alt.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_geo_alt.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_geo_alt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_geo_alt.setObjectName("lbl_mat_geo_alt")
        self.horizontalLayout_3.addWidget(self.lbl_mat_geo_alt)
        self.tbx_mat_geo_alt = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_geo_alt.setObjectName("tbx_mat_geo_alt")
        self.horizontalLayout_3.addWidget(self.tbx_mat_geo_alt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_mat_uuid = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_uuid.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_uuid.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_uuid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_uuid.setObjectName("lbl_mat_uuid")
        self.horizontalLayout.addWidget(self.lbl_mat_uuid)
        self.tbx_mat_uuid = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_uuid.setReadOnly(True)
        self.tbx_mat_uuid.setObjectName("tbx_mat_uuid")
        self.horizontalLayout.addWidget(self.tbx_mat_uuid)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.btn_con_cancel = QtWidgets.QDialogButtonBox(materialDialog)
        self.btn_con_cancel.setOrientation(QtCore.Qt.Horizontal)
        self.btn_con_cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_con_cancel.setObjectName("btn_con_cancel")
        self.gridLayout.addWidget(self.btn_con_cancel, 5, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_mat_number = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_number.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_number.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_number.setObjectName("lbl_mat_number")
        self.horizontalLayout_2.addWidget(self.lbl_mat_number)
        self.tbx_mat_number = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_number.setObjectName("tbx_mat_number")
        self.horizontalLayout_2.addWidget(self.tbx_mat_number)
        self.lbl_mat_name = QtWidgets.QLabel(materialDialog)
        self.lbl_mat_name.setMinimumSize(QtCore.QSize(125, 0))
        self.lbl_mat_name.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lbl_mat_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mat_name.setObjectName("lbl_mat_name")
        self.horizontalLayout_2.addWidget(self.lbl_mat_name)
        self.tbx_mat_name = QtWidgets.QLineEdit(materialDialog)
        self.tbx_mat_name.setObjectName("tbx_mat_name")
        self.horizontalLayout_2.addWidget(self.tbx_mat_name)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 1)

        self.retranslateUi(materialDialog)
        self.btn_con_cancel.accepted.connect(materialDialog.accept)
        self.btn_con_cancel.rejected.connect(materialDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(materialDialog)
        materialDialog.setTabOrder(self.tbx_mat_uuid, self.tbx_mat_number)
        materialDialog.setTabOrder(self.tbx_mat_number, self.tbx_mat_name)
        materialDialog.setTabOrder(self.tbx_mat_name, self.tbx_mat_geo_lat)
        materialDialog.setTabOrder(self.tbx_mat_geo_lat, self.tbx_mat_geo_lon)
        materialDialog.setTabOrder(self.tbx_mat_geo_lon, self.tbx_mat_geo_alt)
        materialDialog.setTabOrder(self.tbx_mat_geo_alt, self.tbx_mat_tmp_bgn)
        materialDialog.setTabOrder(self.tbx_mat_tmp_bgn, self.tbx_mat_tmp_mid)
        materialDialog.setTabOrder(self.tbx_mat_tmp_mid, self.tbx_mat_tmp_end)
        materialDialog.setTabOrder(self.tbx_mat_tmp_end, self.tbx_mat_description)

    def retranslateUi(self, materialDialog):
        _translate = QtCore.QCoreApplication.translate
        materialDialog.setWindowTitle(_translate("materialDialog", "Dialog"))
        self.lbl_mat_tmp_bgn.setText(_translate("materialDialog", "開始時期 : "))
        self.lbl_mat_tmp_mid.setText(_translate("materialDialog", "中間時期 : "))
        self.lbl_mat_tmp_end.setText(_translate("materialDialog", "終了時期 : "))
        self.lbl_mat_description.setText(_translate("materialDialog", "備考 : "))
        self.lbl_mat_geo_lat.setText(_translate("materialDialog", "緯度 : "))
        self.lbl_mat_geo_lon.setText(_translate("materialDialog", "軽度 : "))
        self.lbl_mat_geo_alt.setText(_translate("materialDialog", "標高 : "))
        self.lbl_mat_uuid.setText(_translate("materialDialog", "UUID : "))
        self.lbl_mat_number.setText(_translate("materialDialog", "資料番号 : "))
        self.lbl_mat_name.setText(_translate("materialDialog", "資料の名称 : "))

