# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yufujimoto/GitHub/SurveyDataCollector/ui/recordWithPhotoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_testDialog(object):
    def setupUi(self, testDialog):
        testDialog.setObjectName("testDialog")
        testDialog.resize(800, 601)
        testDialog.setMinimumSize(QtCore.QSize(800, 600))
        self.gridLayout_3 = QtWidgets.QGridLayout(testDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(testDialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setMaximumSize(QtCore.QSize(370, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_snd = QtWidgets.QLabel(self.frame)
        self.lbl_snd.setObjectName("lbl_snd")
        self.verticalLayout_3.addWidget(self.lbl_snd)
        self.lst_snd_fls = QtWidgets.QListWidget(self.frame)
        self.lst_snd_fls.setMinimumSize(QtCore.QSize(0, 0))
        self.lst_snd_fls.setMaximumSize(QtCore.QSize(370, 100))
        self.lst_snd_fls.setObjectName("lst_snd_fls")
        self.verticalLayout_3.addWidget(self.lst_snd_fls)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pbr_l = QtWidgets.QProgressBar(self.frame)
        self.pbr_l.setMaximumSize(QtCore.QSize(50, 100))
        self.pbr_l.setMinimum(0)
        self.pbr_l.setProperty("value", -1)
        self.pbr_l.setAlignment(QtCore.Qt.AlignCenter)
        self.pbr_l.setOrientation(QtCore.Qt.Vertical)
        self.pbr_l.setFormat("")
        self.pbr_l.setObjectName("pbr_l")
        self.gridLayout.addWidget(self.pbr_l, 0, 1, 1, 1)
        self.pbr_r = QtWidgets.QProgressBar(self.frame)
        self.pbr_r.setMinimumSize(QtCore.QSize(0, 50))
        self.pbr_r.setMaximumSize(QtCore.QSize(50, 100))
        self.pbr_r.setProperty("value", 0)
        self.pbr_r.setAlignment(QtCore.Qt.AlignCenter)
        self.pbr_r.setOrientation(QtCore.Qt.Vertical)
        self.pbr_r.setFormat("")
        self.pbr_r.setObjectName("pbr_r")
        self.gridLayout.addWidget(self.pbr_r, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_rec_start = QtWidgets.QPushButton(self.frame)
        self.btn_rec_start.setObjectName("btn_rec_start")
        self.horizontalLayout_3.addWidget(self.btn_rec_start)
        self.btn_rec_stop = QtWidgets.QPushButton(self.frame)
        self.btn_rec_stop.setObjectName("btn_rec_stop")
        self.horizontalLayout_3.addWidget(self.btn_rec_stop)
        self.btn_play = QtWidgets.QPushButton(self.frame)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_3.addWidget(self.btn_play)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.lbl_img = QtWidgets.QLabel(self.frame)
        self.lbl_img.setObjectName("lbl_img")
        self.verticalLayout_3.addWidget(self.lbl_img)
        self.lst_img_icon = QtWidgets.QListView(self.frame)
        self.lst_img_icon.setMaximumSize(QtCore.QSize(370, 16777215))
        self.lst_img_icon.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lst_img_icon.setMovement(QtWidgets.QListView.Static)
        self.lst_img_icon.setResizeMode(QtWidgets.QListView.Adjust)
        self.lst_img_icon.setViewMode(QtWidgets.QListView.IconMode)
        self.lst_img_icon.setObjectName("lst_img_icon")
        self.verticalLayout_3.addWidget(self.lst_img_icon)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(testDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(testDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 1, 1, 1)

        self.retranslateUi(testDialog)
        self.buttonBox.accepted.connect(testDialog.accept)
        self.buttonBox.rejected.connect(testDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(testDialog)

    def retranslateUi(self, testDialog):
        _translate = QtCore.QCoreApplication.translate
        testDialog.setWindowTitle(_translate("testDialog", "Dialog"))
        self.lbl_snd.setText(_translate("testDialog", "録音メニュー"))
        self.label.setText(_translate("testDialog", "L"))
        self.label_2.setText(_translate("testDialog", "R"))
        self.btn_rec_start.setText(_translate("testDialog", "録音する"))
        self.btn_rec_stop.setText(_translate("testDialog", "停止する"))
        self.btn_play.setText(_translate("testDialog", "再生する"))
        self.lbl_img.setText(_translate("testDialog", "画像一覧"))

